modLoader = "javafml"
loaderVersion = "${forge_loaderversion}"
issueTrackerURL = "${mod_git}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"
#logoFile = ""

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_loaderrange}"
ordering = "NONE"
side = "${forge_forgeside}"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_minecraftrange}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "architectury"
mandatory = true
versionRange = "${forge_architecturyrange}"
ordering = "AFTER"
side = "${forge_architecturyside}"
